### PR TITLE
Bumps gitlab version to 6.5 branch

### PR DESCRIPTION
**Pull request by eelcocramer**

### CODE REVIEW

**Comment by eelcocramer** [comment]
Not sure this is ok.

**Comment by eelcocramer** [comment]
It is ok. Add this to the firstrun script to upgrade from 6.4 to 6.5:

```
cd /home/git/gitlab

# Precompile assets
sudo -u git -H bundle install --without development test postgres --deployment

# Start MySQL
mysqld_safe &
sleep 5

# Run database migrations
sudo -u git -H bundle exec rake db:migrate RAILS_ENV=production

# Clean up assets and cache
sudo -u git -H bundle exec rake assets:clean assets:precompile cache:clear RAILS_ENV=production

# Update init.d script
sudo cp lib/support/init.d/gitlab /etc/init.d/gitlab
```

**Comment by moul** [comment]
:+1:

**Comment by eelcocramer** [comment]
Cleaning up.

**Pull request closed without merging**
