### PR TITLE
Moved some commands from firstrun.sh to start.sh to be able to docker run again without `tail -f ... no such file or directory` error

### PR DESCRIPTION
**Pull request by moul**

### CODE REVIEW

**Comment by crashsystems** [comment]
This change would cause these commands to run every time the container
starts, instead of just the first time the container is instantiated. If
you want to create a new instance, you can always restore firstrun.sh via
git checkout.

**Comment by moul** [comment]
Yes I know :) But you can only `docker stop + docker start`
Thanks to this change I am still able to stop + start, but I can also do `docker rm ... + docker run -v /path/to/already-installed-gitlab...` without restoring `firstrun.sh`

Without this change, you can only restore `firstrun.sh` and comment out the cleaning part, but now you can more easily reinstall and keep data, probably update, and you can still restore the `firstrun.sh` to clean data

**Comment by Jackbennett** [comment]
Just bit by this here, not sure why you'd leave the repo in a state I can't re-use. Seems a bit punishing if you want to reload the container with different ports mapped. 

Could you use a firstrun=false env variable to skip the firstrun call on subsequent starts as opposed to on docker run? Or provision this stuff with chef/puppet etc.

**Comment by moul** [comment]
Message from @mbrgm by mail:
`+1 for accepting this.`

**Comment by crashsystems** [comment]
I'll be addressing this with the next update. I tend to handle pull
requests at the same time as I update the build for new GitLab releases,
shortly after the 22nd of each month.

Btw, what would all of you think of a system where when re-creating an
instance and attaching pre-existing data, it automatically handles things
like DB migrations? I'd like to make it so that users don't have to think
about the firstrun script at all.

**Comment by mbrgm** [comment]
@crashsystems: What exactly do you mean when mentioning DB migration? Making firstrun.sh obsolete would be a nice thing, of course.

I think it would also be a good idea to separate the data folder and the rest of the container definition (see http://ijonas.com/devops-2/a-docker-container-folder-structure-thats-flexible-and-scales/). I really like this separation. Container definition can live in source control, other data can reside in a different folder (easier for backups and multiple container deployment, too). For the Gitlab container it would mean having the start.sh script as a static part of the container while dynamically binding the mysql, repos, config.

**Comment by moul** [comment]
I approve your release date strategy and also suggest you to use a _stable_ branch for these releases to be able to process PR as soon as they are appearing

My PR don't talk about the _deletion or not_ of the `firstrun.sh` script and is complementary
I just moved some parts of the `firstrun.sh` to the `start.sh` to address the issue of not being able to `docker run` again pre-existing data

:+1: about the second point!
We should be able to run some automatic checks and `bundle` commands from the `start.sh` script automatically on startup to handle transparent updates

**Comment by mbrgm** [comment]
+1 on the ‚stable‘ branch (or master/develop separation)

**Comment by crashsystems** [comment]
I treat the master branch as stable. If I needed to release an emergency
patch, I'd branch off of master, fix the bug, and merge back in (triggering
rebuild on the index).

**Comment by essa** [comment]
I have written another scripts based on your script.

https://github.com/essa/docker-gitlab

I want to run gitlab with a MySQL server running outside of the Docker container. So I made many changes from you.

I noticed this issue after I uploaded my scripts. But I, too , had to move many commands from firtstrun.sh to start.sh and Dockerfile to make it run because changes to filesystem in the container are not persistent.

**Comment by crashsystems** [comment]
Moul, I was just testing out your commit in my development branch. I tested deleting my instance, and re-running it, at which point I got this error (via docker log):

```
tail: cannot open `/home/git/gitlab/log/production.log' for reading: No such file or directory
```

Did you run into this when testing out your commit?

**Comment by crashsystems** [comment]
Nvm, it turns out that was an unrelated bug, which I just fixed in development. Meanwhile, I'm closing this pull request, as I've just merged your commit into development. I'll be merging development into master (stable branch) shortly, after I make a few more changes.

**Pull request closed without merging**
